<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $with = ['replies'];

    protected $appends = ['askedBy','path'];

    protected $withCount = ['replies'];

    protected $fillable = ['title','category','body','category_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function($question){
            $question->slug = str_slug($question->title);
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getAskedByAttribute()
    {
        return $this->user->name;
    }

    public function getCreatedAtAttribute($value)
    {
        return \Carbon\carbon::parse($value)->diffForHumans();
    }

    public function getPathAttribute()
    {
        return "/read/".$this->category->slug."/".$this->slug;
    }
}
