<?php

namespace App;

use App\Notifications\NewReply;
use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    protected $with = ['user'];

    protected $appends = ['favorited','favorite_count'];

    protected $fillable = ['body','category_id','user_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
       
        static::creating(function ($reply) {
            $reply->user_id = auth()->user()->id;
        });
    }

    public function favorite()
    {
        return $this->hasMany(Favorite::class);
    }

    public function getFavoritedAttribute()
    {
        return !!$this->favorite->where('user_id', auth()->id())->count();
    }

    public function getFavoriteCountAttribute()
    {
        return $this->favorite->count();
    }

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getCreatedAtAttribute($value)
    {
        return \Carbon\carbon::parse($value)->diffForHumans();
    }

    public function notify()
    {
        if ($this->question->user->id !== auth()->id()) {
            $this->question->user->notify(new NewReply($this));
        }
    }
}
